### ISSUE TITLE
Speed Curve Feature

### ISSUE THREAD

**Issue by Aryetis** [gamagora-rushup/rushup#8]

**Comment by mnivoliez** [comment]
We will manage speed by two elements.

1. Inner speed  => muscle power.
  * Default inert value = 0 km/h
  * Base movement value = 10 km/h
  * Max value = 25 km/h
  * Acceleration = +0.5/s
2. Bonus speed => bonus on kill
  * Default = 0 bonus
  * Increase mechanism = +1 upon kill
  * Decrease mechanism = -1 /10s when not accelerating (release key)
  * Reset = upon death

**Comment by Aryetis** [comment]
DONE, since tuesday, wooops
